#!/bin/bash

tower_sqlite3="/Users/$USER/Library/Application Support/Tower/UserRepositories.sqlite3"
git_paths=`sqlite3 -line "$tower_sqlite3" 'SELECT ZPATH FROM ZGCGITREPOSITORY;'`

# Convert the path string to an array
declare -a git_path_array
git_paths=${git_paths//ZPATH = /}
git_path_array=(`echo ${git_paths}`)

# Fix paths containing spaces
for index in "${!git_path_array[@]}"; do
  index_previous=$index
  while [[ "${git_path_array[$index_previous]:0:1}" != "/" ]] && [ $index_previous -gt 0 ]; do
    index_current=$index_previous
    (( index_previous-- ))
    git_path_array[$index_previous]="${git_path_array[$index_previous]} ${git_path_array[$index_current]}"
    git_path_array[$index_current]=""
  done
done

# Fetch remote git data for all paths
for path in "${git_path_array[@]}"; do
  if [[ -e $path ]]; then
    path_remotes="$( cd "$path" && git remote )"
    if [[ -n $path_remotes ]]; then
      # Convert the remotes string to an array
      declare -a git_remote_array
      git_remote_array=(`echo ${path_remotes}`)
      for remote in "${git_remote_array[@]}"; do
        echo "Fetching remote data for $path ($remote)"
        echo "$( cd "$path" && git fetch $remote )"
      done
    fi
  fi
done
